### ISSUE TITLE
MacOS Texifier 无法编译

### ISSUE THREAD

**Issue by evantianzg** [iihciyekub/MUST-Thesis#15]
MacOS，我用Texifier编译显示如下错误：
new_en.tex (行 0)
HTTP response failure: Error Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。" UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x6000078a90e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <27F0A6A6-53A0-4406-BA31-C0DFEB5E380A>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <27F0A6A6-53A0-4406-BA31-C0DFEB5E380A>.<1>"
), NSLocalizedDescription=网络连接已中断。, NSErrorFailingURLStringKey=https://typeset.texpadapp.com/api/5/typeset, NSErrorFailingURLKey=https://typeset.texpadapp.com/api/5/typeset, _kCFStreamErrorDomainKey=4}
其他项目没有这个问题，说明网络没有问题。偶尔没有任何错误或警告，但也无法正常生成pdf。

**Comment by iihciyekub** [comment]
比较抱歉 目前仅维护 overleaf 在线版本, 线下版的话因 latex 编译器版本 系统等问题各异,暂时没作测试与维护

**Comment by evantianzg** [comment]
我原先的Texifier是从App Store下载安装的，现在我换成了从Texifier官网直接下载安装，就没有出现以上问题了。但又出现了新的问题：
fontawesome.sty (行 46)
Package fontspec Error: The font "FontAwesome" cannot be found.
看上去好像是缺失指定的字体，但我并没有在.sty目录下找到fontawesome.sty文件。这可能是什么原因呢？

**Comment by evantianzg** [comment]
> 我原先的Texifier是从App Store下载安装的，现在我换成了从Texifier官网直接下载安装，就没有出现以上问题了。但又出现了新的问题： fontawesome.sty (行 46) Package fontspec Error: The font "FontAwesome" cannot be found. 看上去好像是缺失指定的字体，但我并没有在.sty目录下找到fontawesome.sty文件。这可能是什么原因呢？

报错原因：在路径/usr/local/texlive/2023/texmf-dist/fonts/opentype/public/fontawesome下找到FontAwesome.otf文件。但好像并没有安装。

解决方案：双击该FontAwesome.otf文件即可安装，然后Texifier就可以正确使用FontAwesome字体。
